Repository mayadata-io/oep-e2e-gcp, pull requests merged in 2020-03, with the labels that each got.

#63 (Bug):Renamed file according to gitlab file
  stages/9-openebs-install-check/openebs-install-check
Labels: bug

#59 chore(Readme):Added readme and job file for volume-upgrade
  .gitlab-ci.yml
  stages/10-openebs-upgrade-check/volume-upgrade-jiva-check
  stages/10-openebs-upgrade-check/volume-upgrade-jiva-check.md
Labels: documentation, priority/p0

#57 [iuoi01]- Adding jobs and RAEDME.md for openebs-self-install
  .gitlab-ci.yml
  stages/9-openebs-install-check/openebs-self-installation-check
  stages/9-openebs-install-check/openebs-self-installation-check.md
Labels: priority/p0

#60 Adding openebs control plane test job along with README file
  .gitlab-ci.yml
  stages/9-openebs-install-check/openebs-control-plane-test
  stages/9-openebs-install-check/openebs-control-plane-test.md
Labels: priority/p0

#61 Adding openebs data plane test job along with README file
  .gitlab-ci.yml
  stages/9-openebs-install-check/openebs-data-plane-test
  stages/9-openebs-install-check/openebs-data-plane-test.md
Labels: priority/p0

#70 [iuoi14]:Adding bash script for openebs resource limit installation
  stages/9-openebs-install-check/openebs-resource-limit-installation
Labels: priority/p1

#69 [iuoi06]: Add bash scripts for openebs-reinstallation check test case
  stages/9-openebs-install-check/openebs-reinstallation-test
Labels: priority/p1

#82 update oep to oep-e2e repo
  stages/10-openebs-upgrade-check/pool-upgrade-check
  stages/10-openebs-upgrade-check/upgrade-replica-all-pod-pending-check
  stages/10-openebs-upgrade-check/upgrade-replica-pod-pending
  stages/10-openebs-upgrade-check/upgrade-replica-two-pod-pending
  stages/10-openebs-upgrade-check/volume-upgrade-check
  stages/10-openebs-upgrade-check/volume-upgrade-jiva-check
  stages/3-director-sanity-check/alertmanager-check
  stages/3-director-sanity-check/alertstore-check
  stages/3-director-sanity-check/alertstore-tablemanager-check
  stages/3-director-sanity-check/cassandra-check
  stages/3-director-sanity-check/chat-server-check
  stages/3-director-sanity-check/cloud-agent-check
  stages/3-director-sanity-check/configs-check
  stages/3-director-sanity-check/configs-db-check
  stages/3-director-sanity-check/consul-check
  stages/3-director-sanity-check/distributor-check
  stages/3-director-sanity-check/ingestor-check
  stages/3-director-sanity-check/ingress-nginx-check
  stages/3-director-sanity-check/maya-grafana-check
  stages/3-director-sanity-check/maya-io-server-check
  stages/3-director-sanity-check/maya-ui-check
  stages/3-director-sanity-check/memcached-check
  stages/3-director-sanity-check/mysql-check
  stages/3-director-sanity-check/od-elasticsearch-logging-check
  stages/3-director-sanity-check/od-kibana-logging-check
  stages/3-director-sanity-check/querier-check
  stages/3-director-sanity-check/ruler-check
  stages/3-director-sanity-check/table-manager-check
  stages/3-director-sanity-check/weavescope-check
  stages/4-user-cluster-setup/cluster-create-check
  stages/5-cluster-connect-check/client-components-check
  stages/5-cluster-connect-check/cluster-connect-check
  stages/5-cluster-connect-check/create-apikey-check
  stages/5-cluster-connect-check/self-connect-check
  stages/6-metrics-check/metrics-check
  stages/7-teaming-check/teaming-change-role-check
  stages/7-teaming-check/teaming-change-role-negative-check
  stages/7-teaming-check/teaming-invite-check
  stages/8-topology-check/topology-check
  stages/9-openebs-install-check/openebs-control-plane-test
  stages/9-openebs-install-check/openebs-data-plane-test
  stages/9-openebs-install-check/openebs-install-check
  stages/9-openebs-install-check/openebs-reinstallation-test
  stages/9-openebs-install-check/openebs-resource-limit-installation
  stages/9-openebs-install-check/openebs-self-installation-check
Labels: do-not-merge

#83 [Openebs-Install]: Modified test job script to run pipeline jobs in sequence
  stages/9-openebs-install-check/openebs-control-plane-test
  stages/9-openebs-install-check/openebs-data-plane-test
  stages/9-openebs-install-check/openebs-install-check
  stages/9-openebs-install-check/openebs-reinstallation-test
  stages/9-openebs-install-check/openebs-resource-limit-installation
Labels: bug

#86 Included python script to update readme
  stages/9-openebs-install-check/openebs-install-check
Labels: do-not-merge

#90 [tcid-iuod23]Added bash script for test case pool-upgrade-all-pod-running
  stages/10-openebs-upgrade-check/pool-upgrade-all-pod-running-check
Labels: enhancement

#100 Added new stage RECOMMENDATION-CHECK in gitlab-ci.yml file
  .gitlab-ci.yml
  stages/15-recommendation-check/capacity-recommendation
  stages/15-recommendation-check/device-recommendation
Labels: enhancement

#101 Changed job name for running jobs in sequence
  stages/10-openebs-install-check/openebs-control-plane-test
  stages/10-openebs-install-check/openebs-data-plane-test
  stages/10-openebs-install-check/openebs-install-check
  stages/10-openebs-install-check/openebs-reinstallation-test
  stages/10-openebs-install-check/openebs-resource-limit-installation
Labels: enhancement

#102 Added e2e crd into the bash scripts and refactored the bash scripts.
  stages/10-openebs-install-check/openebs-control-plane-test
  stages/10-openebs-install-check/openebs-data-plane-test
  stages/10-openebs-install-check/openebs-install-check
  stages/10-openebs-install-check/openebs-reinstallation-test
  stages/10-openebs-install-check/openebs-resource-limit-installation
Labels: enhancement
