Repository mayadata-io/oep-e2e-gcp, pull requests merged in 2020-02, with the labels that each got.

#35 adding topology stage and job in the pipeline
  .gitlab-ci.yml
  stages/10-cluster-cleanup/cluster-cleanup
  stages/10-cluster-cleanup/user-cluster-cleanup
  stages/8-topology-check/topology-check
  stages/9-openebs-upgrade-check/openebs-upgrade-check
Labels: enhancement

#56 fix(directory): fix directory structure and add openebs install job
  .gitlab-ci.yml
  stages/10-openebs-upgrade-check/openebs-upgrade-check
  stages/11-e2e-metrics/e2e-metrics
  stages/12-cluster-cleanup/cluster-cleanup
  stages/12-cluster-cleanup/cluster-cleanup.md
  stages/12-cluster-cleanup/user-cluster-cleanup
  stages/12-cluster-cleanup/user-cluster-cleanup.md
  stages/4-user-cluster-setup/cluster-create-check
  stages/9-openebs-install-check/openebs-install
Labels: bug

#53 chore(readme): Add README and scripts for pool and volume upgrade
  .gitlab-ci.yml
  stages/10-openebs-upgrade-check/pool-upgrade-check
  stages/10-openebs-upgrade-check/pool-upgrade-check.md
  stages/10-openebs-upgrade-check/volume-upgrade-check
  stages/10-openebs-upgrade-check/volume-upgrade-check.md
Labels: priority/p0
